services:
  postgres:
    image: postgres:17-alpine
    container_name: bayapay_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - 432:5432
volumes:
  postgres_data:
